feat: rss for blog
nuxt/nuxt.com pull request #1431
Opened 2023-11-21 08:57 UTC by hyoban

2023-11-21 10:03 UTC, manniL requested changes
LGTM besides not relying on `.node`.

One could even go further using `$fetch` to fetch the content for each post, see. e.g @harlan-zw's website @ https://github.com/harlan-zw/harlanzw.com/blob/main/server/util/rss.ts#L6
But that is not always necessary.

2023-11-21 10:03 UTC, manniL commented on server/routes/blog/rss.xml.ts
> +  event.node.res.end(feedString)
In Nitro and H3, the best is not to rely on `.node` but instead use helper methods 😋 
You can also return the result straight away.

```suggestion
  appendHeader(event, 'Content-Type', 'text/xml')
  return feedString
```

2023-11-21 12:25 UTC, manniL commented on server/routes/blog/rss.xml.ts
> +const Copyright = `Copyright © 2016-${ new Date().getFullYear() } Nuxt - MIT License`
Not sure if the Blog contents are licensed under MIT though 🤔

2023-11-21 12:28 UTC, hyoban commented on server/routes/blog/rss.xml.ts
> +const Copyright = `Copyright © 2016-${ new Date().getFullYear() } Nuxt - MIT License`
Change to `Copyright © 2016-${ new Date().getFullYear() } Nuxt All Rights Reserved`?

2023-11-27 15:04 UTC, manniL commented on server/routes/blog/rss.xml.ts
> +const Copyright = `Copyright © 2016-${ new Date().getFullYear() } Nuxt - MIT License`
That's fine for me, yes 👍🏻

2023-11-28 18:07 UTC, Atinux commented
I simplified to avoid using cheerio and adding the content, the user can click on the rss to read on the website, otherwise it's a nightmare with the code blocks and everything.

2023-11-29 09:07 UTC, merged