feat: @nuxt/scripts announcement
nuxt/nuxt.com pull request #1631
Opened 2024-07-24 16:58 UTC by harlan-zw

### 🔗 Linked issue

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Announce https://github.com/nuxt/scripts, work in progress (expect issues).

2024-07-25 02:15 UTC, harlan-zw commented on content/7.blog/24.nuxt-scripts.md
> +The Nuxt team, in collaboration with the [Chrome Aurora](https://developer.chrome.com/aurora) team at Google, are excited to
Yes, this isn't rendered as a line break, you need an empty line for that

2024-07-25 15:42 UTC, housseindjirdeh reviewed
It's coming along nicely!

2024-07-25 15:42 UTC, housseindjirdeh commented on content/7.blog/24.nuxt-scripts.md
> +This slows down the network and blocking the main thread, leading to a degraded user experience and poor [Core Web Vitals](https://web.dev/vitals/).
```suggestion
This slows down the network and blocks the main thread, leading to a degraded user experience and poor [Core Web Vitals](https://web.dev/vitals/).
```

2024-07-25 15:42 UTC, housseindjirdeh commented on content/7.blog/24.nuxt-scripts.md
> +In many cases we're loaded third-party scripts from a domain that we don't control. This can lead to a number of issues:
```suggestion
In many cases we're loading third-party scripts from a domain that we don't control. This can lead to a number of issues:
```

2024-07-25 15:42 UTC, housseindjirdeh commented on content/7.blog/24.nuxt-scripts.md
> +- Everything has to be wrapped for SSR safety
Feel free to ignore, but it might be worthwhile to add a sentence here, or somewhere else in the post, to explain what SSR safety means?

2024-07-25 15:52 UTC, harlan-zw commented on content/7.blog/24.nuxt-scripts.md
> +- Everything has to be wrapped for SSR safety
It makes slightly more sense when viewing it rendered as the first code sample shows you what not being SSR safe looks like and the second one shows you the "safety" but I'll consider making it clearer

2024-07-25 15:57 UTC, harlan-zw commented
Thanks @housseindjirdeh and thanks for the edits, I was planning to send you this once I had a chance to edit for these obvious mistakes :sweat_smile: 

I'm also looking for high-level feedback on anything significant missing from the post (or anything that needs to be removed). From your end do you want TPC mentioned? If so can you give some pointers.

2024-07-29 20:09 UTC, flashdesignory approved these changes
LGTM

2024-07-29 20:09 UTC, flashdesignory commented on content/7.blog/24.nuxt-scripts.md
> +with maximum performance.
nit: if it's a handful of third-parties that use the facade pattern, we could list them here. 
Do you want to give a short description of a facade pattern here and what it solves?

2024-07-29 20:09 UTC, flashdesignory commented on content/7.blog/24.nuxt-scripts.md
> +- [Chrome Aurora](https://developer.chrome.com/aurora) team at Google
nit: should "team at Google" also be in parenthesis?

2024-07-30 02:25 UTC, harlan-zw commented on content/7.blog/24.nuxt-scripts.md
> +The RFC proposed a module which would _allow third-party scripts to be managed and optimized, following best practices for performant and compliant websites_.
i want to use a clear direct quote here and blockquote is a bit too much, I may consider switching to quotes

2024-07-30 21:46 UTC, kara approved these changes
LGTM, with a few nits below. Only comment I really care about is making facade components a bit more visible in the blog post

2024-07-30 21:46 UTC, kara commented on content/7.blog/26.nuxt-scripts.md
> +CrUX data shows Nuxt sites with numerous third-party resources typically show lower [Interaction to Next Paint (INP)](https://web.dev/articles/inp) and [Largest Contentful Paint (LCP)](https://web.de
Nit: your average blog post reader might not be familiar with CrUX. May want to link here (https://developer.chrome.com/docs/crux) or write it out as "Chrome User Experience Report" the first time

2024-07-30 21:46 UTC, kara commented on content/7.blog/26.nuxt-scripts.md
> +CrUX data shows Nuxt sites with numerous third-party resources typically show lower [Interaction to Next Paint (INP)](https://web.dev/articles/inp) and [Largest Contentful Paint (LCP)](https://web.de
Nit: "Lower" here is a bit ambiguous because a lower LCP or INP is a good thing (I think you mean lower pass rates here?). Might be clearer to say "poorer" or something similar

```suggestion
CrUX data shows Nuxt sites with numerous third-party resources typically show poorer [Interaction to Next Paint (INP)](https://web.dev/articles/inp) and [Largest Contentful Paint (LCP)](https://web.dev/articles/lcp) scores.
```

2024-07-30 21:46 UTC, kara commented on content/7.blog/26.nuxt-scripts.md
> +Nuxt Scripts is a better way to work with Third-Party scripts, providing better performance, privacy, security and developer experience.
```suggestion
Nuxt Scripts is a better way to work with third-party scripts, providing better performance, privacy, security and developer experience.
```

2024-07-30 21:46 UTC, kara commented on content/7.blog/26.nuxt-scripts.md
> +While in many cases our hands are tied with the third parties we use, we should try and minimize the amount of our end-users data that we're leaking to third-parties where possible.
Super nit: some of the time, the article mentions "third-parties" with a dash (e.g. line 300 and the second usage here) and other times the dash is omitted (like the first usage here). I'm not sure which is more "right" but probably should be consistent with spelling.

2024-07-30 21:46 UTC, kara commented on content/7.blog/26.nuxt-scripts.md
> +The registry includes several [Facade Components](https://scripts.nuxt.com/docs/guides/facade-components), such as
It would be great to see a full code example with a facade compoennt like Google Maps or YouTube. Just one example would help with a "Facade Components" header. Otherwise, it's pretty easy to miss that they exist.

2024-07-30 21:46 UTC, kara commented on content/7.blog/26.nuxt-scripts.md
> +- [Elemement Event Triggers](/docs/guides/script-triggers#element-event-triggers) - Load scripts based on user interactions such as scrolling, clicking, or form submissions.
```suggestion
- [Element Event Triggers](/docs/guides/script-triggers#element-event-triggers) - Load scripts based on user interactions such as scrolling, clicking, or form submissions.
```

2024-07-30 21:46 UTC, kara commented on content/7.blog/26.nuxt-scripts.md
> +As we saw, there's many opportunities to improve Third-party scripts for developers and end-users.
```suggestion
As we saw, there's many opportunities to improve third-party scripts for developers and end-users.
```

2024-07-31 05:38 UTC, harlan-zw commented
Thank you @kara and @flashdesignory for the feedback, your suggestions should be implemented but lmk if I missed something. I will open this PR up for wider comment.

2024-08-03 15:12 UTC, Atinux commented on content/7.blog/26.nuxt-scripts.md
> +The Nuxt team, in collaboration with the [Chrome Aurora](https://developer.chrome.com/aurora) team at Google, is excited to announce the public beta release of Nuxt Scripts.
```suggestion
The Nuxt team, in collaboration with the [Chrome Aurora](https://developer.chrome.com/aurora) team at Google, is excited to announce the public beta release of [Nuxt Scripts](https://scripts.nuxt.com).
```

2024-08-16 13:28 UTC, danielroe commented on content/7.blog/26.nuxt-scripts.md
> +  useTimeouFn(() => {
```suggestion
  useTimeoutFn(() => {
```

2024-08-16 13:28 UTC, danielroe commented on content/7.blog/26.nuxt-scripts.md
> +  useTimeouFn(() => {
```suggestion
  useTimeoutFn(() => {
```

2024-08-16 13:30 UTC, danielroe commented on content/7.blog/26.nuxt-scripts.md
> +These registry scripts are fine-tuned wrapper around `useScript` with full type-safety, runtime validation of the script options (dev only) and environment variable support
```suggestion
These registry scripts are fine-tuned wrappers around `useScript` with full type-safety, runtime validation of the script options (dev only) and environment variable support
```

2024-08-16 13:30 UTC, danielroe commented on content/7.blog/26.nuxt-scripts.md
> +The registry includes several [Facade components](https://scripts.nuxt.com/docs/guides/facade-components), such as
```suggestion
The registry includes several [facade components](https://scripts.nuxt.com/docs/guides/facade-components), such as
```

2024-08-16 13:30 UTC, danielroe commented on content/7.blog/26.nuxt-scripts.md
> +Nuxt Scripts provides Facade components as accessible but headless, meaning they are not styled by default but add the necessary
```suggestion
Nuxt Scripts provides facade components as accessible but headless, meaning they are not styled by default but add the necessary
```

2024-08-17 07:33 UTC, DamianGlowala requested changes

2024-08-17 07:33 UTC, DamianGlowala commented on content/7.blog/26.nuxt-scripts.md
> +  // 💡 A `defer` script may not available while our Nuxt app hydrates.
```suggestion
  // 💡 A `defer` script may not be available while our Nuxt app hydrates.
```

2024-08-17 07:33 UTC, DamianGlowala commented on content/7.blog/26.nuxt-scripts.md
> +  // ❌ Oops, script hasn't finished loading yet!
```suggestion
  // ❌ Oops, the script hasn't finished loading yet!
```

2024-08-17 07:33 UTC, DamianGlowala commented on content/7.blog/26.nuxt-scripts.md
> +- Adds a proxy layer allowing your app to run when the script's functions in unsafe contexts (SSR, before the script is loaded, script is blocked)
```suggestion
- Adds a proxy layer allowing your app to run when the script functions in unsafe contexts (SSR, before the script is loaded, the script is blocked)
```

2024-08-17 07:33 UTC, DamianGlowala commented on content/7.blog/26.nuxt-scripts.md
> +scripts, with more to come.
```suggestion
The [script registry](https://scripts.nuxt.com/scripts) is a collection of first-party integrations for common third-party scripts. As of release, we support 21 scripts, with more to come.
```

2024-08-17 07:33 UTC, DamianGlowala commented on content/7.blog/26.nuxt-scripts.md
> +or manually calling the `$script.load()` function.
```suggestion
The `useScript` composable gives you full control over how and when your scripts are loaded, by either providing a custom `trigger` or manually calling the `$script.load()` function.
```

2024-08-17 07:33 UTC, DamianGlowala commented on content/7.blog/26.nuxt-scripts.md
> +  // script will only loaded once the consent has been accepted
```suggestion
  // script will only be loaded once the consent has been accepted
```

2024-08-20 10:05 UTC, danielroe approved these changes

2024-08-20 14:53 UTC, merged