docs: zerops guide
nuxt/nuxt.com pull request #1652
Opened 2024-08-29 20:15 UTC by nermalcat69

### 🔗 Linked issue

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

https://zerops.io/ documentation guide

2024-08-29 20:30 UTC, nermalcat69 commented
ahh time for nitro preset

2024-08-30 15:56 UTC, nermalcat69 commented
Pr for nitro preset ✅

2024-09-03 10:21 UTC, Flosciante requested changes

2024-09-03 10:21 UTC, Flosciante commented on content/3.deploy/zerops.md
> +logoIcon: "/assets/integrations/zerops.svg"
@nermalcat69 the image logo isn't showing up. I think it's `logoSrc` here

2024-09-04 16:23 UTC, Flosciante approved these changes

2024-09-04 16:40 UTC, merged